### ISSUE TITLE
Error in DependencyInjection after composer require

### ISSUE THREAD

**Issue by julian-koster** [netgen-layouts/layouts-contentful#12]
Fresh install of layouts-contentful on a Symfony project.
After composer require got the following error on cache clear:

`Warning: file_get_contents(C:\mydir\my-site\vendor\netgen\layouts-core\bundles\LayoutsBundle\DependencyInjection/../Resources/config/C:\mydir\my-site\vendor\netgen\layouts-contentful\bundle\DependencyInjection/../Resources/config/block_type_groups.yaml): Failed to open stream: No such file or directory`

Error originates from:
`vendor/netgen/layouts-core/bundles/LayoutsBundle/DependencyInjection/NetgenLayoutsExtension.php`

Line 178-180:
`if ($configFile[0] !== '/') {
         $configFile = __DIR__ . '/../Resources/config/' . $configFile;
}`
            
Here, if the $configFile does not start with a /, the code is appending '../Resources/config/' before $configFile. This means that if $configFile already contains an absolute path, this line of code is generating an incorrect path.

Fixed it by modifying to:

`if ($configFile[0] !== '/' && !realpath($configFile)) {
       $configFile = __DIR__ . '/../Resources/config/' . $configFile;
}`

**Comment by emodric** [comment]
Fixed with `netgen/layouts-core` 1.4.4.

Thanks @juuuuln for the report!
