### ISSUE TITLE
Error when creating a custom slugger

### ISSUE THREAD

**Issue by weaverryan** [netgen-layouts/layouts-contentful#9]
Hi!

Reproducer is here: https://github.com/weaverryan/netgens-layouts-playing/tree/slugger-error

After setting up things up (database, etc), run:

```
bin/console contentful:sync
```

And you should see:

> Typed property Netgen\Layouts\Contentful\Entity\ContentfulEntry::$remoteEntry must not be accessed before initialization

Coming from: https://github.com/netgen-layouts/layouts-contentful/blob/c2deafe743282f61eb38a7f2b6c1da5ce7ba54f1/lib/Routing/EntrySlugger/Configurable.php#L38

Cheers!

**Comment by emodric** [comment]
Fixed in latest 1.3.x release.
